# Conversion
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "autolink"]

highlighter: rouge

# Uncomment if using alternative renderer
# rdiscount:
#  extensions:
#    - autolink

# kramdown:
#  input: GFM

# Serving
destination: ../../war/docs
exclude: ["img/resources/SiteComponents.png"]

# Variables
product: TellFinder
version: 1.5